import "@/app/globals.sass"
import { fontBody } from "@/libs/fonts"

import Header from "@/components/layouts/Header"
import Footer from "@/components/layouts/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`
          ${fontBody.className}
          bg-white
          text-grey
        `}
      >
        <Header />
          <main>
            {children}
          </main>
        <Footer />
      </body>
    </html>
  )
}
